apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  sources:
    # 1️⃣ Chart source (Bitnami PostgreSQL)
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.0.7
      helm:
        valueFiles:
          - $values/Common/postgresql-values.yaml

    # 2️⃣ Values file source from Git repo
    - repoURL: 'https://github.com/maheshgowdamg/Databases.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

