apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.mattermost: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: "true"
    notifications.argoproj.io/subscribe.on-outofsync.mattermost: "true"

spec:
  project: default

  destination:
    namespace: dev
    server: https://kubernetes.default.svc

  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.1.3
      helm:
        valueFiles:
          - $values/Common/postgresql-values.yaml
        values: |
          image:
            repository: bitnamilegacy/postgresql
            tag: 16.3.0-debian-12-r19

          volumePermissions:
            enabled: true
            image:
              repository: bitnamilegacy/os-shell

          metrics:
            enabled: true
            pgStatStatements: true
            image:
              repository: bitnamilegacy/postgres-exporter

          primary:
            extraEnvVars:
              - name: BITNAMI_DEBUG
                value: "false"

          readReplicas:
            replicaCount: 2

    - repoURL: "https://github.com/maheshgowdamg/Databases.git"
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
