apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    # REMOVED the undefined triggers.
    # ONLY subscribing to the one you have defined.
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: ""

spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "this-tag-does-not-exist"
      helm:
        valueFiles:
          - $values/Common/postgresql-values.yaml
    - repoURL: 'https://github.com/maheshgowdamg/Databases.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
