apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
data:
  mongodb-root-password: c3VwZXJzZWNyZXQ=         # base64 for 'supersecret'
  mongodb-replica-set-key: cmVwbGljYXNldGtleTEyMw== # base64 for 'replicasetkey123'
