
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: dev
type: Opaque
stringData:
  # Database credentials
  postgres-password: "admin123"         # Superuser password
  password: "appuser123"                # App user password
  replication-password: "replica123"    # Replication user password
